#! /bin/bash

for user in user{51..70}
do
	id ${user} &> /dev/null
	exists=$?

	if [ ${exists} -eq 0 ]
	then
		echo "Given user exists!!"
	else
		echo "Given user doesn't exist!!"
		echo -e "Adding user ${user}\n"
		adduser --disabled-password ${user} --gecos "${user}" &> /dev/null # due to this line we have to run the script with sudo privileges
		echo "${user}:${user}_@123" | chpasswd &> /dev/null
	fi
done
