#!/bin/bash

read -p "Enter username: "

id ${REPLY} &> /dev/null

if [ $? -eq 0 ]
then
	echo "User ${REPLY} exists!!"

else
	echo "User ${REPLY} doesnot exist!!"
	echo "Creation of user ${REPLY} commencing!!"
	read -s -p "Please enter password for user ${REPLY}: " PASSWD

	if [ -z ${PASSWD} ] # type "man test" to know about -z option
	then
		echo -e "\nUser creation for user ${REPLY} aborted!!" # type "man echo" to know about options like -e
	else
		adduser --disabled-password ${REPLY} --gecos "" &> /dev/null
		echo "${REPLY}:${PASSWD}" | chpasswd
		echo -e "\nuser ${REPLY} created successfully!!"
	fi

fi
